### ISSUE TITLE
Bad gateway reproductie

### ISSUE THREAD

**Issue by Bramm** [SeasoningDev/Seasoning#241]
Ik heb een vrij consequente manier gevonden om deze te reproduceren:
1. Ik log mij in en begin aan ingredient te werken.
2. Ik open een nieuwe tab Seasoning (waar ik dan niet aangemeld ben).
3. Ik meld mij aan met de Google-knop
4. Ik klik op de ingredientenlijst en krijg de error 9/10 keer.

**Comment by Gargamel1989** [comment]
Dit komt door lage ram op de server.

Kan ook interessant zijn om app verder te optimaliseren tot minder ram gebruik
