### ISSUE TITLE
Browser compatibility

### ISSUE THREAD

**Issue by Bramm** [SeasoningDev/Seasoning#284]
Net bij een collega gaan kijken (die was geïnteresseerd) naar Seasoning.
Had Safari en gaf de recepten een beetje anders weer.

Ben daarop gaan browsertesten op https://seasoning.be/recipes/

Issues:
Windows 7ie 8: raar recepten toevoegen logo
Windows XPchrome 25: middenste rij recepten niet op gelijke hoogte
Windows 7firefox 3.6: raar recepten toevoegen logo
iPhone 4S(portrait): mogelijk slechte footer
iPhone 5(portrait): mogelijk slechte footer
Windows XPie 7: te checken - zag er algemeen raar uit (kan aan test gelegen hebben)
iPad 3rd (6.0)(portrait): middenste rij recepten niet op gelijke hoogte
Amazon Kindle Fire 2(portrait): recepten niet op gelijke hoogte
OS X Snow Leopardsafari 5.1: middenste rij recepten niet op gelijke hoogte
OS X Mountain Lionchrome 26: middenste rij recepten niet op gelijke hoogte

**Comment by Gargamel1989** [comment]
IE compatibility zou ok moeten zijn:

IE10-11: Werkt perfect
IE9: werkt naar behoren, transities en andere eye candy doen het niet
IE8 en lager: fuck deze shit, laat een alert zien dat de seasoning niet werkt met deze versie en dat de user best zijn browser upgrade

**Comment by Gargamel1989** [comment]
Chrome compatibility zou ok moeten zijn:

Chrome46: Getest, kon niet direct iets vinden dat niet werkt
Chrome45: niet getest, maar zou normaal hetzelfde moeten zijn als 46 (ik heb de release notes bekeken ja)

Alle andere chromes worden niet echt meer gebruikt

**Comment by Gargamel1989** [comment]
Ipad compatibility zou ok moeten zijn:

Safari (versie ongekend maar niet de nieuwste): werkt naar behoren, transities doen het niet, balken schuiven niet mee naar beneden
