### ISSUE TITLE
Chrome compabiliteit van iconenbalk recepten view

### ISSUE THREAD

**Issue by Bramm** [SeasoningDev/Seasoning#317]

**Comment by Gargamel1989** [comment]
Niks mis mee voor zover ik kan zien...

**Comment by Bramm** [comment]
Tekst hangt buiten kader. Doe hier een test op de /recipes/ pagina. Zelfde fout zit ook op IE, iPhone, Samsung, en Firefox 30 ziet er ook niet 100% uit
