### ISSUE TITLE
Grafiek 2

### ISSUE THREAD

**Issue by SeasoningDev** [SeasoningDev/Seasoning#325]
3 tabs
gauss curves met categorie/ven-veg-nveg/alle recepten en het huidige recept aangeduid

**Comment by SeasoningDev** [comment]
Ik wil dit uitstellen naar 1.2/2.0 en wel om volgenden redenen:

- We zijn helemaal niet zeker dat de voetafdrukken een normaalverdeling gaan volgen, en we kunnen dit met de data die we nu hebben ook nog niet checken
- ons plan van voorlopig gewoon het gemiddelde en de standaardafwijking van onze huidige data te berekenen en daarmee een gauscurve op te stellen is niet nuttig. Dit geeft bv. recepten een kans van 40% om een voetafdruk van 0 te hebben.
- Blijkbaar zijn er helemaal niet zoveel fenomenen (zeker geen die beinvloedbaar zijn door de mens) die een normale verdeling hebben

Ik stel dus voor van voorlopig te wachten tot we meer recepten hebben (lees: EVA gescraped hebben) en beter kunnen zien wat voor een verdeling we werkelijk hebben. Dan kunnen we nog zien wat we ermee doen

**Comment by Bramm** [comment]
Ok
