### ISSUE TITLE
Veiligheidscertificaat verlopen

### ISSUE THREAD

**Issue by Bramm** [SeasoningDev/Seasoning#333]

**Comment by SeasoningDev** [comment]
fukken done

**Comment by Bramm** [comment]
Geraak er van het werk nog niet op zonder uitzondering toe te voegen..

**Comment by SeasoningDev** [comment]
Ok, nu werkt het. Aantekeningen:

- We gaan €8 per jaar moeten betalen voor een ssl certificaat, wat belachelijk cheap is :D, ik stuur u de factuur door
- Voor dev.seasoning.be zult ge een veiligheidsuitzondering moeten toevoegen, gezien het certificaat daar niet voor werkt, maar dat is dus volgens verwachting, geen schrik hebben

**Comment by Bramm** [comment]
In orde.
