### ISSUE TITLE
tekstjes en afbeeldingen homepage not logged in bespreken en afmaken

### ISSUE THREAD

**Issue by SeasoningDev** [SeasoningDev/Seasoning#336]

**Comment by Bramm** [comment]
Ik ga mij hier aan zetten, maar ik ga wel al zeggen dat ik niet te ver wil afwijken van wat er nu op Seasoning staat, aangezien daar lang over nagedacht is geweest en mij dat ook niet zo slecht lijkt. Het enige dat ik wel wil doen, is heel die bazaar wat inkorten en eventueel wat andere info erop zetten.
