### ISSUE TITLE
Bugs in not logged in homepage

### ISSUE THREAD

**Issue by SeasoningDev** [SeasoningDev/Seasoning#340]
* Onderste titeltjes zijn nog cursief
* Chrome:
  * spaties tussen 2de deel blokken en pijlen naar beneden is weg
  * laatste slide is niet goed gealigned
  * dun lijntje tussen laatste afbeelding en footer
* 2de deel titel gaat over navigatie

**Comment by Gargamel1989** [comment]
kunde eens nagaan of deze er nog zijn? Volgens mij heb ik ze allemaal opgelost

**Comment by Bramm** [comment]
Ik test als ik thuis op Chrome ben

**Comment by Bramm** [comment]
Ok, ik ben gewoon even op Firefox aan het kijken - denk niet dat ze per se Chrome-specifiek waren:

- Onderste titeltjes zijn nog altijd cursief (Recepten vergelijken - hoe werkt het - ...).
- Ga naar homepage notlogged in: klik achtereenvolgens op alle pijltjes. Bij het laatste pijltje komt er een stuk van de onderste afbeelding mee naar boven.
- Ik ben nog altijd voorstander van het aanpassen van de onderste foto - de lijn met de 2e is te hard. Ofwel moet er een soort overgangsbalk komen (zoals de Wat is Seasoning? balk), ofwel een afbeelding met een gelijkaardig kleurenschema
- Dat dun groen lijntje is er nog steeds (zie screenshot)

**Comment by Bramm** [comment]
- Voorstel onderste foto: Brownies 1 (pot met chocolade en boter) - lijkt me beter over te gaan in de foto erboven.
