### ISSUE TITLE
plaatsing totale voetafdruk bespreken

### ISSUE THREAD

**Issue by SeasoningDev** [SeasoningDev/Seasoning#344]
De 'totale voetafdruk' staat daar een beetje verloren. Weglaten? To discuss neem ik aan. Eventueel kan die naast de 'porties' gezet worden, dan zie je ook meteen het effect van de porties aanpassen op de totale voetafdruk.

**Comment by Bramm** [comment]
Ik heb het gevoel dat ge hiermee akkoord ging, maar dat ge geen betere plaats kon bedenken. Alleszins, ik denk dat 1 van de 2 dingen niet goed staat (ofwel de tekst, ofwel het getal).

Wat ook een optie is: de tekst weglaten en boven het getal een soort dikke lijn zetten. Het lijkt mij dan automatisch duidelijk dat het om de totale voetafdruk gaat?
