### ISSUE TITLE
recipe summaries mooier maken

### ISSUE THREAD

**Issue by Gargamel1989** [SeasoningDev/Seasoning#358]

**Comment by Gargamel1989** [comment]
Well, I tried...

**Comment by Bramm** [comment]
Vind het al veel beter :-). Ik ga hier een paar ideetjes opwerpen als dat ok is:

- Komt het aantal 'lekkers' in de rechteronderhoek (zo neen, zou ik wel fan van zijn - maar ik vermoed dat dit al gepland is)
- De lintjes komen bij mij nog altijd een klein beetje pixelachtig over (vooral de inner circle)
- Klein klokje voor het aantal minutren zetten (zie Yummly)?
- Gebruiker die heeft toegevoegd of oorspronkelijke website/blog toevoegen (zie ook Yummly)? Dit enkel als ge dat zelf echt ziet zitten - hoeft voor mij niet
- Waarom ging de korte beschrijving ook alweer weg? Ik weet dat dit een beslissing is die ooit genomen is, maar ik mis ze een klein beetje - nu lijkt het té beknopt
- Lobster doet pijn aan mijn ogen (negeer dit maar - maar ik moet het gezegd hebben)
