### ISSUE TITLE
"Sorteren op"-functie niet compatibel met Chrome, IE, ...

### ISSUE THREAD

**Issue by Bramm** [SeasoningDev/Seasoning#361]
Tekst hangt buiten kader. Doe hier een test op de /recipes/ pagina. Zelfde fout zit ook op IE, iPhone, Samsung, en Firefox 30 ziet er ook niet 100% uit

**Comment by Gargamel1989** [comment]
Lijkt te werken? kan het niet reproduceren. De sorteerfunctie is ook redelijk hard veranderd natuurlijk
