### ISSUE TITLE
Scrapen voedingscentrum

### ISSUE THREAD

**Issue by Bramm** [SeasoningDev/Seasoning#362]
Ik ben dit mss vergeten te zeggen, maar Voedingscentrum heeft gezegd dat we content mits bronvermelding mogen overnemen: http://www.voedingscentrum.nl/recepten/receptenzoeker/zoekresultaten.aspx?isBalans=1&dieetID=3

**Comment by Gargamel1989** [comment]
Jammer genoeg geen afbeeldingen
