### ISSUE TITLE
Recepten pagina

### ISSUE THREAD

**Issue by Bramm** [SeasoningDev/Seasoning#372]
- Ik vind die balk nog altijd te donker. Kunt ge eens het grijs proberen dat ge krijgt als ge over de 'registreer nu!' knop hovert?

- De zoek recepten balk zou ik centreren (verticaal).

- Hebt ge een toekomstvisie voor het geavanceerd zoeken? Want nu is er ineens wel heel wat functionaliteit verloren gegaan.

- En nu moet ik het toch nog eens gezegd hebben: ik vind de lobster niet mooi en ik mis zelfs de korte samenvatting. De vooruitgang op Seasoning 1.0 is dat het wolkje weg is (sterk verbeterd door lintje) en dat de onderste balk lichtgroen ipv zwart is. Voor de rest vond ik 1.0 echt goed. Ik vind de 1.1 momenteel nogal kaal.

**Comment by Gargamel1989** [comment]
Lik mijn ballen
