### ISSUE TITLE
Recepten view pagina

### ISSUE THREAD

**Issue by Bramm** [SeasoningDev/Seasoning#373]
- Tooltip Voetadruk: ik zou het woord ecologisch weglaten -> ik meen mij te herinneren dat we hier eens over gediscussieerd hebben en daardoor de Over Seasoning pagina moesten aanpassen. Daarin staat nu gewoon 'Voetafdruk' ipv Ecologische voetafdruk.

- Dit is ineens ne rare, maar ik krijg het gevoel dat gebruikers mss gaan denken dat die pijlen aan de zijkant er niet zijn om tussen afbeeldingen te scrollen, maar om naar het volgende recept te gaan -> hetgeen ik ook nog wel vet zou vinden, want dan zou ge die afbeeldingen ervan lichter gekleurd tot aan de borders van het scherm kunnen laten gaan (Seasoning 2.0 materiaal - if anything).

**Comment by Gargamel1989** [comment]
1e is niet meer relevant, als ge het 2de nog altijd 2.0 materiaal vindt, moogt ge altijd een nieuwe issue aanmaken
