### ISSUE TITLE
Kwaliteit lintjes

### ISSUE THREAD

**Issue by Bramm** [SeasoningDev/Seasoning#379]
Ik heb nu een vb gevonden op onze Facebook. De lintjes waren vroeger effectief beter, kijk:
![knipsel](https://cloud.githubusercontent.com/assets/3428052/6269693/374fd1a4-b855-11e4-9177-214986edc54a.PNG)
![knipsel2](https://cloud.githubusercontent.com/assets/3428052/6269692/374f2cae-b855-11e4-9f54-39347cf6ecd6.PNG)

**Comment by Gargamel1989** [comment]
gelukkig niet meer van toepassing
