### ISSUE TITLE
Who backups the backups?

### ISSUE THREAD

**Issue by Gargamel1989** [SeasoningDev/Seasoning#385]

**Comment by Gargamel1989** [comment]
Nope, fix dit

**Comment by Gargamel1989** [comment]
https://www.youtube.com/watch?v=dSpOjj4YD8c

**Comment by Bramm** [comment]
Ok, ik heb hier luidop mee moeten lachen :D

**Comment by JoepDriesen** [comment]
:D

Date: Thu, 12 Nov 2015 14:34:51 -0800
