### ISSUE TITLE
Aparte reeks issues voor content

### ISSUE THREAD

**Issue by Bramm** [SeasoningDev/Seasoning#396]
Is het eventueel niet mogelijk om ook mijn taken/issues op Github te zetten? Dan hoef ik dat niet apart bij te houden.

Ik weet dat Github daar niet voor gemaakt is, maar lijkt mij wel makkelijker

**Comment by SeasoningDev** [comment]
Gij moogt doen wat ge wilt, maak gewoon een nieuw label 'content' en tag al uw issues daarmee...

**Comment by Bramm** [comment]
danku lieve Joep
